### ISSUE TITLE
Cannot read property 'getSelection' of undefined

### ISSUE THREAD

**Issue by EasonWang01** [sstur/react-rte#136]
hi,this is a good editor,but how to solve this?

thanks.

**Comment by dave-cheong** [comment]
I encountered the same issue which I was able to resolve by adding an `exclude` clause to Babel in my `webpack.config`. For me, it was something like so:

`      
{test: /\.jsx?$/, exclude: /node_modules/, loaders: ['babel?compact=false']},
`

Note this was only an issue when I use webpack directly. I did not have this issue in my other apps when I used `Create React App` directly.

**Comment by daviel** [comment]
Had the same problem. Console put:

> [BABEL] Note: The code generator has deoptimised the styling of "/home/user/app/node_modules/react-rte/dist/react-rte.js" as it exceeds the max of "500KB".

which was leading to the error messages in the debugging console. After adding ignore to my .babelrc the problem was solved.

{
  "presets": ["es2015", "react"],
  **"ignore": "/node_modules/"**
}

Hope it helps.

**Comment by ngryman** [comment]
Still having the issue using Rollup.

It seems that `global` is undefined because Webpack injects `this` as the global. In non-strict mode `this` is set to `window`. But in strict mode it's set to `undefined`. Because I'm bundling everything and I have a global `use strict` statement, this fails hard.

Would it be possible to not rely on `this` using Webpack?
