### ISSUE TITLE
Mobile View Editing Bug

### ISSUE THREAD

**Issue by mariacheline** [sstur/react-rte#257]
When you switch to mobile view the editor is completely unuseful.
You can type but as soon as you hit space or enter, the text editor clears out.

**Comment by misenesi** [comment]
You might have a bug in your code, works fine for me.

**Comment by mariacheline** [comment]
Testing it on an Android phone

**Comment by noahshaf** [comment]
Ran into the same problem on Android - Android 8.0, Pixel XL.

**Comment by GeDrax** [comment]
Same issue on Android 7.1.2 MIUI 9

**Comment by wyamout** [comment]
any update on  this? same issue

**Comment by dmarkrollins** [comment]
Mobile not yet support (as of this post) according to Facebook so your mileage will vary.

https://draftjs.org/docs/advanced-topics-issues-and-pitfalls.html

**Comment by noahshaf** [comment]
Here is a longish discussion of the problem. Affects all draftjs users, not just react-rte

https://github.com/facebook/draft-js/issues/1077

**Comment by Ggayane** [comment]
2019 - Still having this problem 😞

**Comment by ScottLindley** [comment]
This has since been fixed with the latest draft-js release [v0.11.0](https://github.com/facebook/draft-js/releases/tag/v0.11.0).
[draft-js issue](https://github.com/facebook/draft-js/issues/1895)
[draft-js PR](https://github.com/facebook/draft-js/pull/2035)

react-rte should publish a new release updating this dependency to resolve this issue.

**Comment by NNSTH** [comment]
I'm using react-rte with draft-js version: 0.11.6 and still having a lot of issues on Android devices.
are you sure this had been fixed the issues?

**Comment by ScottLindley** [comment]
@NNSTH I'm certainly not sure. I can only say that this issue was resolved for my team after the release I mentioned. I probably should have worded it that way when I originally posted last year.

**Comment by NNSTH** [comment]
thanks for your reply, can you tell me which version do you use? or did you add any other fixes for that case?

**Comment by ScottLindley** [comment]
@NNSTH unfortunately for this thread we are now using [slate](https://github.com/ianstormtaylor/slate) in place of `react-rte`. While I don't have a lot of context into why we made that change, I am fairly sure it wasn't because of this singe open issue.
The comments above indicate the issue may lie not in `react-rte`, but `draft-js`, so I might suggest you go knock on that door.

I hope this gets resolved for you!

**Comment by NNSTH** [comment]
@ScottLindley thanks, I'll try understand more from draft-js threads.

**Comment by sstur** [comment]
Hey @ScottLindley, glad to hear you had some success by making the switch. As I understand it, this is a long-running issue with the underlying draft-js implementation and it's non-trivial to fix without core changes.

I think Slate is probably a good choice for many use cases that aren't well served by draft-js, on which this editor is built.

Sorry there's not a better answer to this : (

**Comment by Diaver** [comment]
The issue still here :(

**Comment by adarsh1021** [comment]
I am facing issues on android phone with google keyboard when:
- pressing enter key, the cursor behaves unpredictably. Sometimes goes to next line. Sometimes jumps to the line before
- formatting options like bulleting are also not consistent
