### ISSUE TITLE
Support for onBlur

### ISSUE THREAD

**Issue by RainFang** [sstur/react-rte#46]
I was wondering if React-RTE supported onBlur?

passing in my onBlur function as a prop doesn't seem to work, and I was hoping to run a save function onBlur. Any ideas?

Thanks!

**Comment by RainFang** [comment]
Closing this. It appears that the editor doesn't support onBlur.

Currently solving this by wrapping the editor in a div with onBlur. If I have time, I'll put in a pull request for onBlur.

**Comment by sstur** [comment]
I'll re-open this because we should support onBlur so this is essentially a feature request. Thanks!

**Comment by sstur** [comment]
I believe this is fixed in 21da9a4 which will go out with the next `npm publish`.

**Comment by alexxmde** [comment]
It seems that this is not fixed. The object passed to onBlur looks different from the one passed to onChange. Using the toString function, it returns [Object object] instead of the value.
It looks like that what's being passed to onBlur is an event with a target on the editor's div. I can't figure out how to retrieve the value
